package com.example.startProject.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Person {
//    id to be generated by DB
    private Integer id;
    private String firstName;
    private String LastName;
    private Integer age;

    private String dob;



}
